project:
  type: website
  output-dir: docs

website:
  title: "Hayden Vega"
  favicon: images/logo.png
  site-url: https://haydenvega.github.io/
  google-analytics: 
    tracking-id: "G-KTFM8KEX8J"
    anonymize-ip: true
  navbar:
    title: false
    logo: images/logo.png
    css: styles.scss
    right:
      - href: index.qmd
        text: home # use 'text' option to update the name as you want it to appear in your navbar
      - href: research.qmd
        text: research
      - href: posts.qmd
        text: outreach
      - href: fieldwork.qmd
        text: fieldwork
      - href: words.qmd
        text: words
      - href: cv_hv.pdf
        text: cv
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/haydenvega
  page-footer:
    background: dark
    left: Hayden Vega
    right:
      - icon: github
        href: https://github.com/haydenvega
      - icon: linkedin
        href: https://www.linkedin.com/in/hayden-vega-6893a3207/
  
format:
  html:
    sidebar: false
    theme: 
      - jolla
      - styles.scss
    mainfont: Lexend
    toc: true