project:
  type: website
  output-dir: docs

website:
 site-url: https://haydenvega.github.io/
 navbar:
    title: "Hayden Vega" # this is the website title as it appears in the top left corner -- clicking on this will jump you back to your landing page from where ever you are
    favicon: images/Logo maker project.png
    navbar:
    title:  false
    logo: images/Logo maker project.png
    logo-alt: "Alt text for logo"
    right:
      - href: index.qmd
        text: Home # use 'text' option to update the name as you want it to appear in your navbar
      - about.qmd
      - href: resources.qmd
        text: Resources
      - href: cv_hv.pdf
        text: CV
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/haydenvega
 page-footer:
    background: dark
    left:
      - "Hayden Vega"
    right:
      - icon: github
        href: https://github.com/haydenvega
      - icon: linkedin
        href: https://www.linkedin.com/in/hayden-vega-6893a3207/
  #page-footer:
   # background: dark # or light
    #left:
     # - "Hayden Vega"
    #right:
     # - icon: github
      #  href: https://github.com/haydenvega
      #- icon: envelope
       # href: mailto:haydenvega@ucsb.edu

format:
  html:
    theme: 
    - styles.scss
    mainfont: Marcellus
    toc: true

editor: visual

