project:
  type: website
  output-dir: docs

website:
  title: "Hayden Vega"
  site-url: https://haydenvega.github.io/
  favicon: images/logo.png
  
 navbar:
    title: false
    logo: images/logo.png
    logo-alt: "Alt text for logo"
    right:
      - href: index.qmd
        text: Home # use 'text' option to update the name as you want it to appear in your navbar
      - about.qmd
      - href: resources.qmd
        text: Resources
      - href: cv_hv.pdf
        text: CV
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/haydenvega
 page-footer:
    background: dark
    left: Hayden Vega
    right:
      - icon: github
        href: https://github.com/haydenvega
      - icon: linkedin
        href: https://www.linkedin.com/in/hayden-vega-6893a3207/
  
format:
  html:
    page-layout: full
    sidebar: false
    theme: jolla
    css: styles.css
    mainfont: Marcellus
    toc: true